export interface BookCitation {
  id: string;
  text: string;
  source: string;
  url?: string;
  urlStatus: "verified" | "unverified";
  severity?: number;
}

export const bookCitations: Record<string, BookCitation> = {
  "HC-007": {
    id: "HC-007",
    text: "Google's Project Aristotle study of 180 teams found psychological safety — the ability to speak freely without fear of consequence — to be the top predictor of team effectiveness across every metric studied.",
    source: "Google",
    url: "https://rework.withgoogle.com/guides/understanding-team-effectiveness/steps/introduction/",
    urlStatus: "verified",
    severity: 5,
  },
  "HC-068": {
    id: "HC-068",
    text: "Edmondson's foundational 1999 study establishing team psychological safety — the shared belief that interpersonal risk-taking is safe — as a direct predictor of learning behavior and team performance.",
    source: "Administrative Science Quarterly",
    url: "https://journals.sagepub.com/doi/10.2307/2666999",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-070": {
    id: "HC-070",
    text: "Edmondson and Kerrissey (2025) correct six persistent misconceptions about psychological safety, including the dangerous conflation of safety with comfort and the idea that safe teams avoid hard truths.",
    source: "Harvard Business Review",
    url: "https://hbr.org/2025/05/what-people-get-wrong-about-psychological-safety",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-071": {
    id: "HC-071",
    text: "Five-year study of strategy execution finding that fewer than 10% of companies achieve all strategic objectives, with broken cross-functional coordination as the primary failure point — not a flawed strategy.",
    source: "Harvard Business Review",
    url: "https://hbr.org/2015/03/why-strategy-execution-unravels-and-what-to-do-about-it",
    urlStatus: "verified",
    severity: 3,
  },
  "HC-110": {
    id: "HC-110",
    text: "Gallup research showing employees who receive daily feedback are 3.6x more likely to feel motivated to do outstanding work, and 80% of employees who received meaningful feedback in the past week describe themselves as fully engaged.",
    source: "Gallup",
    url: "https://www.gallup.com/workplace/357764/fast-feedback-fuels-performance.aspx",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-103": {
    id: "HC-103",
    text: "Keltner's research on power and social cognition finds that elevated status systematically impairs the neural processes underlying social attentiveness — people with power become less accurate at reading emotions, less likely to take others' perspectives, and less responsive to social feedback over time.",
    source: "Keltner, Dacher. The Power Paradox. Penguin Press, 2016.",
    urlStatus: "verified",
    severity: 3,
  },
  "HC-ROSS-1977": {
    id: "HC-ROSS-1977",
    text: "The Fundamental Attribution Error describes the pervasive cognitive bias wherein observers systematically overemphasize dispositional traits and underestimate situational or structural influences when diagnosing the causes of failure.",
    source: "Ross, L. (1977). The Intuitive Psychologist and His Shortcomings: Distortions in the Attribution Process. Advances in Experimental Social Psychology, 10, 173-220.",
    url: "https://www.sciencedirect.com/science/article/pii/S006526010860357X",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-GREEN-1979": {
    id: "HC-GREEN-1979",
    text: "The two-stage attributional model of leadership establishes that supervisors systematically misattribute poor subordinate performance to internal traits rather than external conditions, leading to punitive behavioral interventions rather than structural corrections.",
    source: "Green, S. G., & Mitchell, T. R. (1979). Attributional Processes of Leaders in Leader-Subordinate Interactions. Organizational Behavior and Human Performance, 23(3), 429-458.",
    url: "https://www.sciencedirect.com/science/article/pii/0030507379900084",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-SWIFT-2013": {
    id: "HC-SWIFT-2013",
    text: "Even highly experienced professionals suffer from correspondence bias in evaluation, systematically failing to discount performance advantages conferred by favorable situational and structural environments.",
    source: "Swift, S. A., Moore, D. A., Sharek, Z. S., & Gino, F. (2013). Inflated Applicants: Attribution Errors in Performance Evaluation by Professionals. PLoS ONE, 8(7), e69258.",
    url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0069258",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-REASON-1990": {
    id: "HC-REASON-1990",
    text: "The Swiss Cheese Model demonstrates that visible 'active failures' by individuals are merely symptoms; the true root causes of systemic failure are 'latent conditions' — dormant structural weaknesses embedded in organizational architecture by management decisions.",
    source: "Reason, J. (2000). Human error: models and management. BMJ, 320(7237), 768-770.",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC1070929/",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-SENGE-1990": {
    id: "HC-SENGE-1990",
    text: "The 'Shifting the Burden' systems archetype illustrates how applying rapid symptomatic solutions temporarily reduces visible distress but diverts resources away from fundamental structural fixes, eventually eroding the organization's capacity for systemic resolution.",
    source: "Senge, P. M. (1990). The Fifth Discipline: The Art and Practice of the Learning Organization. Doubleday/Currency.",
    url: "https://thesystemsthinker.com/shifting-the-burden-moving-beyond-a-reactive-orientation/",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-HUGHES-2011": {
    id: "HC-HUGHES-2011",
    text: "The widely repeated statistic that 70% of organizational change initiatives fail is an unsupported narrative lacking valid, reliable empirical evidence at its source — traced to an explicitly unscientific 1993 estimate, then repeated without verification.",
    source: "Hughes, M. (2011). Do 70 Per Cent of All Organizational Change Initiatives Really Fail? Journal of Change Management, 11(4), 451-464.",
    url: "https://doi.org/10.1080/14697017.2011.630506",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-DEWAAL-2026": {
    id: "HC-DEWAAL-2026",
    text: "An integrative evidence synthesis of failure-rate claims in improvement and transformation initiatives finds reported rates vary widely and are not comparable unless definitions, denominators, and time horizons are specified — most repetition of a ~70% figure traces to secondary citation rather than recalculated rates.",
    source: "de Waal, A. (2026). Beyond the 70% myth: What do we actually know about failure rates in improvement and transformation initiatives?",
    url: "https://scindeks-clanci.ceon.rs/data/pdf/2334-9638/8888/2334-96388800002D.pdf",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-SAKS-2006": {
    id: "HC-SAKS-2006",
    text: "Longitudinal evaluation of training transfer demonstrates a steep behavioral regression to baseline when unsupported by environmental conditions: 62% of learned behaviors are applied immediately, decaying to 44% at six months, and dropping to 34% at one year.",
    source: "Saks, A. M., & Belcourt, M. (2006). An investigation of training activities and transfer of training in organizations. Human Resource Management, 45(4), 629-648.",
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1002/hrm.20135",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-SAJJADIANI-2024": {
    id: "HC-SAJJADIANI-2024",
    text: "A study of 1,620 retail stores found that when a high-performing employee voluntarily quits, turnover among the remaining high performers rises 6% per month for the following three months — a cumulative 18% increase — while turnover among low performers actually declines over the same period.",
    source: "Sajjadiani, S., Kammeyer-Mueller, J., & Benson, A. Academy of Management Journal, 2024.",
    url: "https://blogs.lse.ac.uk/businessreview/2024/03/13/when-a-high-performer-leaves-the-firm-loses-more-than-a-good-worker/",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-HOUSMAN-MINOR-2015": {
    id: "HC-HOUSMAN-MINOR-2015",
    text: "A study of over 50,000 workers across 11 firms found that the induced turnover cost of retaining one toxic worker — driven by increased departures among coworkers — averages $12,489, more than double the cost-savings benefit of hiring a top-1%-productivity \"superstar\" worker ($5,303). The same study found a worker's exposure to toxic colleagues measurably increases that worker's own likelihood of being terminated for toxic behavior.",
    source: "Housman, M., & Minor, D. Harvard Business School Working Paper 16-057, 2015.",
    url: "https://www.hbs.edu/ris/Publication%20Files/16-057_d45c0b4f-fa19-49de-8f1b-4b12fe054fea.pdf",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-GRIFFIN-HAUSER-1996": {
    id: "HC-GRIFFIN-HAUSER-1996",
    text: "A review and analysis of fifteen empirical studies on cross-functional integration found that organizations achieving higher levels of collaboration and information-sharing between specialized functions consistently produced better outcomes than those left to operate independently — while specialization without corresponding integration mechanisms reliably produced measurable coordination costs and conflict between departments.",
    source: "Griffin, A., & Hauser, J. R. (1996). Integrating R&D and Marketing: A Review and Analysis of the Literature. Journal of Product Innovation Management, 13(3), 191-215.",
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/1540-5885.1330191",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-ARGYRIS-1990": {
    id: "HC-ARGYRIS-1990",
    text: "Argyris's research on organizational learning found that when problems arise, the people most responsible for the underlying strategy typically do not examine their own role in producing the problem. Instead, they attribute it to external conditions — market shifts, unrealistic timelines, poor execution — through what he termed defensive routines, which protect against embarrassment or threat at the cost of blocking the root-cause analysis that would resolve the problem.",
    source: "Argyris, C. Overcoming Organizational Defenses: Facilitating Organizational Learning. Allyn & Bacon, 1990.",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-GILBOA-KAHN-ROLE": {
    id: "HC-GILBOA-KAHN-ROLE",
    text: "A meta-analysis of role stress research found role ambiguity has a moderate negative relationship with job performance and a measurable positive association with turnover intention, building on Kahn and colleagues' original 1964 framework establishing role ambiguity as a primary source of organizational stress.",
    source: "Gilboa, S., Shirom, A., Fried, Y., & Cooper, C. Personnel Psychology, 2008. Building on Kahn, R., Wolfe, D., Quinn, R., Snoek, J., & Rosenthal, R. Organizational Stress: Studies in Role Conflict and Ambiguity. Wiley, 1964.",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-MCKINSEY-DECISIONS-2019": {
    id: "HC-MCKINSEY-DECISIONS-2019",
    text: "A McKinsey survey of more than 1,200 managers found that respondents who reported their decision-making was fast were nearly twice as likely to also report their decisions were high quality — directly contradicting the common assumption that speed and quality trade off against each other. The same research estimated that ineffective decision-making wastes more than 500,000 days of managerial time annually at a typical Fortune 500 company, equivalent to roughly $250 million in wages.",
    source: "De Smet, A., Lurie, M., & St George, A. McKinsey & Company, \"Three keys to faster, better decisions,\" 2019.",
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/three-keys-to-faster-better-decisions",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-ANSOFF-1975": {
    id: "HC-ANSOFF-1975",
    text: "Igor Ansoff's foundational 1975 framework on \"weak signals\" established that organizations which can detect and act on faint, ambiguous indicators of change before those indicators have formed a clear pattern gain a measurable strategic advantage over organizations that wait for a fully-formed, unambiguous signal before acting — a tradeoff between earlier, less certain action and later, more certain but more costly action.",
    source: "Ansoff, H. I. (1975). Managing Strategic Surprise by Response to Weak Signals. California Management Review, 18(2), 21-33.",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-NLRB-CHIPOTLE-2016": {
    id: "HC-NLRB-CHIPOTLE-2016",
    text: "The NLRB found that Chipotle violated federal labor law when supervisors enforced an outdated social media policy against an employee — even though the company had already replaced it with a compliant version — ruling that reliance on stale documentation does not excuse the resulting violation. The remedy required reinstatement with back pay and enterprise-wide rescission of the outdated language.",
    source: "Chipotle Services LLC, 364 NLRB No. 72 (2016)",
    url: "https://www.nlrb.gov/case/04-CA-147314",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-SCOTUS-FARAGHER-1998": {
    id: "HC-SCOTUS-FARAGHER-1998",
    text: "The Supreme Court held that an employer's anti-harassment policy provides no liability shield if it was never effectively disseminated to the employees it was meant to protect — the City of Boca Raton's policy existed on paper but was unknown to the work unit where the harassment occurred, and the Court found this failure alone defeated the employer's affirmative defense as a matter of law.",
    source: "Faragher v. City of Boca Raton, 524 U.S. 775 (1998)",
    url: "https://www.law.cornell.edu/supct/html/97-282.ZO.html",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-NYCLL144-2023": {
    id: "HC-NYCLL144-2023",
    text: "NYC Local Law 144 requires employers using automated employment decision tools (AEDTs) to substantially assist or replace hiring or promotion decisions to commission an independent bias audit within the prior year and publicly post a summary before use, with penalties of $500 to $1,500 per violation per day.",
    source: "NYC Local Law 144 (2021), enforced by the NYC Department of Consumer and Worker Protection, effective July 2023.",
    url: "https://www.osc.ny.gov/state-agencies/audits/2025/12/02/enforcement-local-law-144-automated-employment-decision-tools",
    urlStatus: "verified",
    severity: 2,
  },
  "HC-MOBLEY-2024": {
    id: "HC-MOBLEY-2024",
    text: "Mobley v. Workday allowed the claim that an AI hiring vendor can be directly liable as an 'agent' of the employers using its screening tools to survive motion to dismiss — establishing that AI-vendor liability theories can proceed to discovery, not that liability has been found on the merits. The case remains in active litigation as of mid-2026, with claims proceeding under FEHA, the ADA, and a certified nationwide ADEA collective action.",
    source: "Mobley v. Workday, Inc., No. 3:23-cv-00770 (N.D. Cal.)",
    url: "https://www.courtlistener.com/docket/66831340/175/mobley-v-workday-inc/",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-SIXTH-BABB-2019": {
    id: "HC-SIXTH-BABB-2019",
    text: "A CRNA was terminated for cited clinical errors, but an email sent hours after her termination attributed the decision to her worsening eyesight. The Sixth Circuit reversed summary judgment for the employer, holding this was 'smoking gun' evidence that the employer regarded her as disabled under the ADA — reaffirming that an employer cannot fire someone because it perceives them as disabled, even if that perception is mistaken.",
    source: "Babb v. Maryville Anesthesiologists, P.C., 942 F.3d 308 (6th Cir. 2019)",
    url: "https://law.justia.com/cases/federal/appellate-courts/ca6/19-5148/19-5148-2019-11-06.html",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-THIRD-TICE-2001": {
    id: "HC-THIRD-TICE-2001",
    text: "A bus driver alleged his employer improperly commingled his medical certifications with his general personnel file, violating the ADA's separate confidential medical file requirement. The Third Circuit affirmed summary judgment for the employer, holding that a private plaintiff must show actual damage or tangible injury — such as an unauthorized party viewing the records — to prevail on a confidentiality claim; a technical commingling violation alone is not independently actionable by a private party, though it remains directly enforceable by the EEOC without any injury requirement.",
    source: "Tice v. Centre Area Transportation Authority, 247 F.3d 506 (3d Cir. 2001)",
    url: "https://caselaw.findlaw.com/court/us-3rd-circuit/1054873.html",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-SCOTUS-MURRAYUBS-2024": {
    id: "HC-SCOTUS-MURRAYUBS-2024",
    text: "The Supreme Court held, unanimously, that a whistleblower bringing a claim under the Sarbanes-Oxley Act's retaliation provision need only show that protected activity was a 'contributing factor' in an adverse action — not that the employer acted with retaliatory intent or animus. Once a contributing factor is shown, the burden shifts entirely to the employer to prove by clear and convincing evidence it would have taken the same action regardless. This is a substantially more lenient causation standard than Title VII's, meaning close timing between a report and an adverse action can carry significant weight without requiring proof of intent.",
    source: "Murray v. UBS Securities, LLC, 601 U.S. 23 (2024)",
    url: "https://www.law.cornell.edu/supremecourt/text/22-660",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-MITCHELLWOOD-1980": {
    id: "HC-MITCHELLWOOD-1980",
    text: "An empirical test of the leader-attribution model found that supervisors consistently explain a subordinate's poor performance by pointing at the subordinate's own low effort or ability rather than at task design, resourcing, or conflicting priorities -- and respond more punitively the more times the pattern repeats, with the initial attribution driving the intervention chosen rather than the reverse.",
    source: "Mitchell, T. R., & Wood, R. E. (1980). Supervisor's Responses to Subordinate Poor Performance: A Test of an Attributional Model. Organizational Behavior and Human Performance, 25(1), 123-138.",
    url: "https://www.sciencedirect.com/science/article/abs/pii/003050738090029X",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-HEINRICH-1931": {
    id: "HC-HEINRICH-1931",
    text: "Heinrich's analysis of over 75,000 industrial accident reports concluded that roughly 88% of workplace accidents were caused by unsafe acts on the part of workers rather than unsafe conditions -- a finding that shaped decades of industrial safety practice, though later researchers have challenged both his methodology and the specific ratio.",
    source: "Heinrich, H. W. (1931). Industrial Accident Prevention: A Scientific Approach. McGraw-Hill.",
    url: "https://en.wikipedia.org/wiki/Herbert_William_Heinrich",
    urlStatus: "verified",
    severity: 1,
  },
  "HC-BLUME-2010": {
    id: "HC-BLUME-2010",
    text: "A meta-analytic review of 89 empirical studies on transfer of training found that a supportive post-training work environment is a significant predictor of whether newly learned behavior is sustained on the job, while unsupported training shows steep decay within months.",
    source: "Blume, B. D., Ford, J. K., Baldwin, T. T., & Huang, J. L. (2010). Transfer of Training: A Meta-Analytic Review. Journal of Management, 36(4), 1065-1105.",
    url: "https://journals.sagepub.com/doi/10.1177/0149206309352880",
    urlStatus: "verified",
    severity: 1,
  },
};
