export type BookContentType = "memo" | "methodology" | "case_pattern";
export type BookVoice = "standard" | "from_the_author";

export interface BookPiece {
  id: string;
  slug: string;
  contentType: BookContentType;
  voice: BookVoice;
  title: string;
  teaser: string;
  signatureId?: string;
  citationIds?: string[];
  relatedSlug?: string;
  author: "Principal Resolution";
  status: "draft" | "published" | "parked";
  scheduledWeek?: number;
  scheduledDay?: "Tue" | "Thu" | "Fri";
  contentPillar?: "Reframe" | "Pattern Named" | "Case Composited" | "Underneath" | "Foundation";
}

export const bookManifest: BookPiece[] = [
  {
    id: "LIB-020",
    slug: "candor-as-an-organizational-variable",
    contentType: "methodology",
    voice: "standard",
    title: "Candor as an Organizational Variable: What It Is, How It Degrades, and What the Instrument Reads",
    teaser: "Candor is not a personality trait or a cultural value statement. It is a measurable organizational condition with known degradation patterns and known consequences for diagnostic accuracy.",
    citationIds: ["HC-007", "HC-110"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 1,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-021",
    slug: "symptoms-states-and-why-the-distinction-matters",
    contentType: "methodology",
    voice: "standard",
    title: "Symptoms, States, and Why the Distinction Matters for Practice",
    teaser: "Organizations present with symptoms. The instrument diagnoses states. Understanding why those are different things — and why treating one without identifying the other produces recurrence — is foundational to how Principal Resolution works.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 8,
    scheduledDay: "Tue",
    contentPillar: "Underneath",
  },
  {
    id: "LIB-025",
    slug: "when-the-data-points-at-the-person-who-hired-you",
    contentType: "methodology",
    voice: "standard",
    title: "When the Data Points at the Person Who Hired You",
    teaser: "The diagnostic implicates leadership. The person who hired you is sitting across from you. What happens in the next twenty-four hours will define the engagement more than anything that came before it.",
    citationIds: ["HC-068", "HC-070"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 2,
    scheduledDay: "Tue",
    contentPillar: "Underneath",
  },
  {
    id: "LIB-026",
    slug: "the-problem-they-brought-you-is-not-always-the-problem",
    contentType: "methodology",
    voice: "standard",
    title: "The Problem They Brought You Is Not Always the Problem",
    teaser: "Clients arrive with a theory. The diagnostic arrives with a finding. Understanding why those two things diverge — and how to navigate the gap without losing the client — is one of the hardest skills in the work.",
    citationIds: ["HC-071"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 3,
    scheduledDay: "Thu",
    contentPillar: "Underneath",
  },
  {
    id: "LIB-027",
    slug: "how-to-tell-if-the-organization-will-actually-change",
    contentType: "methodology",
    voice: "standard",
    title: "How to Tell If the Organization Will Actually Change",
    teaser: "Every organization that hires a practitioner believes it is ready to change. Learning to distinguish genuine readiness from its performance — before the engagement is half over — is one of the most valuable skills in the work.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 4,
    scheduledDay: "Fri",
    contentPillar: "Underneath",
  },
  {
    id: "LIB-028",
    slug: "what-their-resistance-is-actually-telling-you",
    contentType: "methodology",
    voice: "standard",
    title: "What Their Resistance Is Actually Telling You",
    teaser: "Resistance is not the end of an engagement's productive life. It is often the beginning of it. What the organization is pushing back against tells you more about where the work needs to go than anything it has said directly.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 6,
    scheduledDay: "Fri",
    contentPillar: "Underneath",
  },
  {
    id: "LIB-030",
    slug: "earned-effectiveness-conversation-framework",
    contentType: "methodology",
    voice: "standard",
    title: "The Earned Effectiveness Conversation Framework: Sequence, Accuracy, and What the Practice Debrief Reads",
    teaser: "Effectiveness in a hard conversation is never assumed and never forced — it is earned through a disciplined sequence. This piece explains the framework and what the four practice debrief dimensions are actually measuring.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 13,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-034",
    slug: "earned-effectiveness",
    contentType: "methodology",
    voice: "standard",
    title: "Earned Effectiveness",
    teaser: "Most practitioners know how to be direct. Fewer know how to be direct in a way that produces change rather than defense. The gap between those two outcomes is not a matter of courage or clarity — it is a matter of sequence.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 15,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "FTA-17",
    slug: "anchor",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Anchor",
    teaser: "The Anchor is the rarest finding in the diagnostic system — not because healthy organizations are rare, but because they don't usually go looking. What you built is real, it's valuable, and it's more fragile than it looks.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 17,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "LIB-014",
    slug: "anchor-problem",
    contentType: "memo",
    voice: "standard",
    title: "The Anchor Problem",
    teaser: "Anchor is the state that names what happens when a role, a person, or a structure that once worked has not been updated to match what the organization has become. The drag compounds quietly — and adaptation is not resolution.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 2,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-013",
    slug: "exit-calculation",
    contentType: "memo",
    voice: "standard",
    title: "The Exit Calculation",
    teaser: "The people who left were not wrong. They were just the first to finish the math. The ones still here are running the same calculation — and they are watching to see what you do next.",
    relatedSlug: "exit-pattern",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 4,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-015",
    slug: "feedback-nobody-wants-to-say",
    contentType: "memo",
    voice: "standard",
    title: "The Thing About Feedback Nobody Wants to Say",
    teaser: "The corporate feedback apparatus has become extraordinarily sophisticated at creating the appearance of feedback without producing the substance of it. The problem is not the tools — we confused delivery infrastructure with candor.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 6,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-016",
    slug: "psychological-safety-walked-into-a-meeting",
    contentType: "memo",
    voice: "standard",
    title: "Psychological Safety Walked Into a Meeting",
    teaser: "This is not an argument against psychological safety. It is an argument against what most organizations have done with a genuinely useful idea — deploy it in exactly the environments where it cannot survive.",
    citationIds: ["HC-068"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 7,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-017",
    slug: "hr-is-the-table",
    contentType: "memo",
    voice: "standard",
    title: "HR Is the Table",
    teaser: "The 'seat at the table' argument was always asking for the wrong thing. HR is not seeking entry into a room where decisions are being made. HR is the architecture that makes the room possible.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 8,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-035",
    slug: "organizational-assessment",
    contentType: "memo",
    voice: "standard",
    title: "Organizational Assessment",
    teaser: "An organizational assessment sends someone in with no position in the organization, no relationships to protect, and no stake in what the findings turn out to be. What it produces is a diagnosis — not a set of recommendations designed to be palatable.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 12,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-036",
    slug: "organizational-assessment-methodology",
    contentType: "methodology",
    voice: "standard",
    title: "Organizational Assessment: Methodology",
    teaser: "Most consulting engagements begin with a hypothesis — and the investigation confirms it. Three principles that correct for this: look without an agenda, report what you actually found, and deliver something specific enough to act on.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 13,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-037",
    slug: "organizational-assessment-sop",
    contentType: "methodology",
    voice: "standard",
    title: "Organizational Assessment: Engagement SOP",
    teaser: "The full engagement sequence for an organizational assessment — five phases, none compressible — with guidance for the circumstances where something in the engagement doesn't fit the expected pattern.",
    author: "Principal Resolution",
    status: "parked",
  },
  {
    id: "FTA-03",
    slug: "succession-planning",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Succession Planning",
    teaser: "The difference between a succession plan and a succession wish — and what organizational continuity actually requires you to be able to answer.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 3,
    scheduledDay: "Fri",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-06",
    slug: "business-case",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Business Case",
    teaser: "Business cases aren't predictions. They're arguments optimized for approval — and the system that rewards the confident version over the accurate one keeps producing the same outcomes.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 8,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-10",
    slug: "accountability",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Accountability",
    teaser: "Accountability doesn't collapse all at once. It erodes through exceptions — each one defensible in isolation, accumulating into a permission structure that everyone can see and no one has addressed.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 12,
    scheduledDay: "Tue",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-11",
    slug: "matrix-organization",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Matrix Organization",
    teaser: "The matrix doesn't eliminate reporting conflict. It relocates it downward — to the person with the least power to resolve it — and calls that structure.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 12,
    scheduledDay: "Fri",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-12",
    slug: "toxic-culture",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Toxic Culture",
    teaser: "Toxic cultures don't announce themselves. They teach you the rules the old-fashioned way — by making examples — and become stable long before anyone decides to address them.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 13,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-01",
    slug: "the-untouchable",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Untouchable",
    teaser: "You know exactly who it is. You've done the math on what it's costing. Leadership has done the math too — and decided the answer is to keep waiting. That calculation is almost always wrong.",
    citationIds: ["HC-HOUSMAN-MINOR-2015"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 1,
    scheduledDay: "Tue",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-02",
    slug: "leadership-deafness",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Leadership Deafness",
    teaser: "The leader who talks about transparency and shuts down the moment someone tests it. The feedback that stopped reaching them years ago. The gap between who they think they are and what the room experiences.",
    citationIds: ["HC-103"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 2,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-04",
    slug: "no-margin-for-error",
    contentType: "methodology",
    voice: "from_the_author",
    title: "No Margin for Error",
    teaser: "You already know it's bad. The buffer is gone. The people who could help you fix this are the ones who have already left. The window is real — and it is not going to stay open while you think about it.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 5,
    scheduledDay: "Fri",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-05",
    slug: "exit-pattern",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Identity Erosion",
    teaser: "Another one just put in notice. The exit interviews say 'opportunity.' The real story is what they tell their friends six months later, once they have nothing to lose. You are not losing people randomly. You are losing people in a pattern.",
    relatedSlug: "exit-calculation",
    citationIds: ["HC-SAJJADIANI-2024"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 7,
    scheduledDay: "Tue",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-07",
    slug: "the-basement-standard",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Basement Standard",
    teaser: "Everyone knows. Nobody says anything. The organization decided, without ever really deciding, that avoiding conflict is more important than solving problems. The cost is invisible until it isn't.",
    citationIds: ["HC-110"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 9,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-08",
    slug: "silosolation",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Silosolation",
    teaser: "The organization has fractured into self-contained units that have learned to function without each other. Each team is doing fine on their own. The whole is producing less than the sum of its parts — and the gap between the two is where your best people are slowly burning out.",
    citationIds: ["HC-GRIFFIN-HAUSER-1996"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 10,
    scheduledDay: "Fri",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-09",
    slug: "the-broken-compass",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Broken Compass",
    teaser: "The offsite was great. Everyone left feeling aligned. That was three months ago. Since then, the same agreed strategy has been interpreted six different ways — and nobody has acknowledged the contradiction because acknowledging it would require having the conversation that nobody wants to have.",
    citationIds: ["HC-ARGYRIS-1990"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 11,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-13",
    slug: "decision-paralysis",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Decision Paralysis",
    teaser: "The meeting moves. The agenda advances. Everyone nods. You walk out and realize nothing was actually decided. Again. This is not professionalism — it is the language of thoughtfulness deployed in the service of permanent deferral.",
    citationIds: ["HC-MCKINSEY-DECISIONS-2019"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 14,
    scheduledDay: "Tue",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-14",
    slug: "the-undefined-role",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Undefined Role",
    teaser: "The org chart you drew at twenty people does not work at eighty. The roles blurred in motion, the workarounds became the system, and the people who absorbed the gap are now the first ones running the math on how much longer they can sustain it.",
    citationIds: ["HC-GILBOA-KAHN-ROLE"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 15,
    scheduledDay: "Thu",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-15",
    slug: "the-policy-lag",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Policy Lag",
    teaser: "You are not failing because you are bad at your job. You are failing because you are running today's operations on infrastructure built for a different organization. The process was good once. That organization no longer exists.",
    citationIds: ["HC-NLRB-CHIPOTLE-2016", "HC-SCOTUS-FARAGHER-1998"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 16,
    scheduledDay: "Tue",
    contentPillar: "Reframe",
  },
  {
    id: "FTA-16",
    slug: "the-lost-map",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Lost Map",
    teaser: "You are not sure what is wrong. You are sure something is. The signals are present but have not formed a pattern yet. That ambiguity is frustrating — and it is also the most valuable moment to be paying attention.",
    citationIds: ["HC-ANSOFF-1975"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 16,
    scheduledDay: "Fri",
    contentPillar: "Reframe",
  },
  {
    id: "LIB-018",
    slug: "everyone-is-defensive-and-no-one-knows-why",
    contentType: "memo",
    voice: "standard",
    title: "Everyone Is Defensive and No One Knows Why",
    teaser: "You have started preparing for conversations that should take five minutes. Feedback stopped being a tool and became a risk — not because anyone decided that, but through small, accumulated signals that added up to something legible: raising difficult things here costs more than staying quiet.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 10,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-019",
    slug: "the-room-that-never-pushes-back",
    contentType: "memo",
    voice: "standard",
    title: "The Room That Never Pushes Back",
    teaser: "Your meetings go smoothly. Proposals land well. Nobody raises objections you haven't already thought of. A room that never pushes back is not a room full of people who agree with you — it is a room full of people who have decided that disagreeing with you costs more than it returns.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 11,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-022",
    slug: "what-the-organization-decided-he-was-worth",
    contentType: "case_pattern",
    voice: "standard",
    title: "What the Organization Decided He Was Worth",
    teaser: "A director. A CEO friendship. An HR function without standing. Two women who followed the process exactly as designed — and found out what the process was built to protect. The complaint worked. That was the problem.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 1,
    scheduledDay: "Fri",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-023",
    slug: "the-first-one-out-the-door",
    contentType: "case_pattern",
    voice: "standard",
    title: "The First One Out the Door",
    teaser: "She had been there six years. When she resigned, the executive director said it was a loss but that he understood. What he did not do — what nobody did — was ask her what she had been watching for the last eighteen months.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 3,
    scheduledDay: "Tue",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-024",
    slug: "why-your-team-stopped-disagreeing-with-you",
    contentType: "memo",
    voice: "standard",
    title: "Why Your Team Stopped Disagreeing with You",
    teaser: "You put a real question to your senior team — one where you genuinely expected the table to split — and instead you got unanimous agreement. You are left wondering whether you just got consensus or whether you got a performance of it. Those are not the same thing.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 11,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-029",
    slug: "the-resignation-that-ended-a-department",
    contentType: "case_pattern",
    voice: "standard",
    title: "The Resignation That Ended a Department",
    teaser: "She had been there eleven years — long enough to become the person who keeps an organization functioning in ways nobody thought to measure. The restructuring disrupted something invisible. She raised it in March. She resigned in April. What the transition checklist could not capture left with her.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 4,
    scheduledDay: "Thu",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-031",
    slug: "what-ready-didnt-include",
    contentType: "case_pattern",
    voice: "standard",
    title: "What Ready Didn't Include",
    teaser: "She was not excluded. She was simply not included at the moment when inclusion would have changed something. That distinction matters — because the first version of the problem is about intent, and the second is about structure. Intent is easy to defend. Structure is what actually determines what information reaches a decision.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 6,
    scheduledDay: "Thu",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-032",
    slug: "one-exception-at-a-time",
    contentType: "case_pattern",
    voice: "standard",
    title: "One Exception at a Time",
    teaser: "The strategy was real. The exceptions were reasonable. By the fourth exception, no one was calling them exceptions anymore. Drift is not a single decision — it is the product of many reasonable decisions that no one ever accounted for together.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 7,
    scheduledDay: "Fri",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-033",
    slug: "built-for-comfort",
    contentType: "case_pattern",
    voice: "standard",
    title: "Built for Comfort",
    teaser: "He had not been wrong often. Over thirty years, that accumulated into something that looked like wisdom and functioned like a wall. He did not construct the architecture deliberately. He maintained it passively, one comfortable hire at a time.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 9,
    scheduledDay: "Tue",
    contentPillar: "Case Composited",
  },
  {
    id: "LIB-043",
    slug: "anatomy-of-resentment",
    contentType: "memo",
    voice: "standard",
    title: "The Anatomy of Resentment",
    teaser: "It starts with a disagreement about the work. The most dangerous shift is when that disagreement becomes a judgment about the person — and the organization learns to route around what it will not name.",
    relatedSlug: "the-basement-standard",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 15,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-044",
    slug: "effectiveness-dies-in-darkness",
    contentType: "memo",
    voice: "standard",
    title: "Effectiveness Dies in Darkness",
    teaser: "The most visible indicator of silosolation is not conflict between departments. It is the absence of it. When units have learned to function without each other, the gap at the handoff is where coordination fails and your best work never gets done.",
    relatedSlug: "silosolation",
    citationIds: ["HC-GRIFFIN-HAUSER-1996"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 16,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-045",
    slug: "cost-of-flying-blind",
    contentType: "memo",
    voice: "standard",
    title: "The Cost of Flying Blind",
    teaser: "The clearest signal of a broken compass is not disagreement about strategy. It is agreement that doesn't produce coordinated action. The organization left the offsite aligned. Three months later, nobody is executing the same strategy.",
    relatedSlug: "the-broken-compass",
    citationIds: ["HC-ARGYRIS-1990"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 17,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-046",
    slug: "risk-of-family-friction",
    contentType: "memo",
    voice: "standard",
    title: "The Risk of Family Friction",
    teaser: "The org chart says Vice President. The actual governance document says something different. Any organization running on authority structures built for a different version of itself is paying a lag cost — and the informal structures are always the last thing anyone is willing to name.",
    relatedSlug: "the-policy-lag",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 17,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-047",
    slug: "velocity-of-truth",
    contentType: "memo",
    voice: "standard",
    title: "The Velocity of Truth",
    teaser: "Decision latency is the gap between when a truth becomes available and when anyone acts on it. Most organizations are running at enormous decision latency and not tracking it. The cost is real. It just doesn't appear on any balance sheet.",
    relatedSlug: "decision-paralysis",
    citationIds: ["HC-MCKINSEY-DECISIONS-2019"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 18,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-048",
    slug: "politeness-tax",
    contentType: "memo",
    voice: "standard",
    title: "The Politeness Tax",
    teaser: "Every person in the organization who holds an opinion that would require uncomfortable delivery is running a calculation. In a high-politeness culture, the cost of uncomfortable delivery is systematically higher — and the role ambiguity it leaves in place compounds with every cycle of growth.",
    relatedSlug: "the-undefined-role",
    citationIds: ["HC-GILBOA-KAHN-ROLE"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 18,
    scheduledDay: "Thu",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-049",
    slug: "intellectual-bottleneck",
    contentType: "memo",
    voice: "standard",
    title: "The Intellectual Bottleneck",
    teaser: "There is a leadership profile that appears in high-performing organizations with unsettling regularity. The person built something real. And then, at a certain point, the organization stopped growing faster than they can think. The ceiling is not imposed on them. They are the ceiling.",
    relatedSlug: "leadership-deafness",
    citationIds: ["HC-103"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 18,
    scheduledDay: "Fri",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-050",
    slug: "crisis-as-catalyst-for-clarity",
    contentType: "methodology",
    voice: "standard",
    title: "Crisis as a Catalyst for Clarity",
    teaser: "The organizations that call at this stage have usually been building toward it for longer than they know. What the work looks like when an organization is already in structural collapse — and why the instinct to tighten control is exactly wrong.",
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 19,
    scheduledDay: "Tue",
    contentPillar: "Pattern Named",
  },
  {
    id: "LIB-051",
    slug: "why-blaming-the-person-almost-never-fixes-the-problem",
    contentType: "methodology",
    voice: "standard",
    title: "Why Blaming the Person Almost Never Fixes the Problem",
    teaser: "The impulse to look for a person before looking for a structure is not a leadership failing. It is a well-documented cognitive default — and acting on it without checking first produces a specific kind of waste that organizations pay for, on a delay, in the next hire.",
    citationIds: ["HC-ROSS-1977", "HC-SWIFT-2013", "HC-GREEN-1979", "HC-REASON-1990", "HC-SENGE-1990", "HC-SAKS-2006"],
    author: "Principal Resolution",
    status: "published",
    scheduledWeek: 19,
    scheduledDay: "Fri",
    contentPillar: "Foundation",
  },
  {
    id: "FTA-18",
    slug: "the-overloaded-manager",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Overloaded Manager",
    teaser: "Three years ago she managed six people and ran the best team in the building. The org chart absorbed the growth. Nobody decided this on purpose — and now you're looking at her numbers wondering what changed about her, when nothing did.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-19",
    slug: "the-unformed-leader",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Unformed Leader",
    teaser: "He was the best individual contributor on the team, so you made him the manager of it. The instincts that made him excellent at the job don't transfer to leading it — and the development you already tried wasn't built for what he actually needed.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-20",
    slug: "the-dormant-talent",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Dormant Talent",
    teaser: "Ask him what each person on his team needs to grow and he'll tell you, specifically. He's also done nothing about it in eighteen months. Knowing isn't the same as doing — and a manager who can name the gap and doesn't close it is a more complete failure than one who simply doesn't know.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-21",
    slug: "decision-blindness",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Decision Blindness",
    teaser: "A complaint came in four months ago. Since then, four individually defensible decisions happened to the person who raised it. Nobody has examined them together — and the correction window that's still open right now is closing on a schedule the organization doesn't control.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-22",
    slug: "what-nobody-says",
    contentType: "methodology",
    voice: "from_the_author",
    title: "What Nobody Says",
    teaser: "The meeting ends and everyone agreed. Twenty minutes later, in the parking lot, your people are having the real conversation — the one that would have changed the plan if it had happened in the room. Smooth meetings aren't evidence of health. They're often evidence the friction moved somewhere you're not.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-23",
    slug: "heard-and-ignored",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Heard & Ignored",
    teaser: "She did it the right way — used the actual channel, exactly as the handbook described. Nothing happened. Everyone who watched what happened to her report has drawn the same conclusion: the channel doesn't actually do anything.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-24",
    slug: "the-suppression-filter",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Suppression Filter",
    teaser: "You stopped telling your manager the full picture a while ago — not because you're hiding anything, but because you watched what happens to bad news once it enters this organization. By the time it reaches someone who could act, it doesn't look like the thing you actually reported.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-25",
    slug: "culture-drift",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Culture Drift",
    teaser: "Nobody decided this. No policy changed. The words on the wall are the same words that were there three years ago — but a recent survey found ninety-one percent still believe the values are officially in force while seventy-four percent believe leadership doesn't actually operate by them.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-26",
    slug: "the-burned-credibility",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Burned Credibility",
    teaser: "The first broken commitment got an explanation. The second got a more skeptical one. By now, the next announcement about what's going to be different will land in a room that has already decided not to believe it — and credibility doesn't come back through a better pitch.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-27",
    slug: "pay-exposure",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Pay Exposure",
    teaser: "She knows she's underpaid. Her manager probably does too. The organization has the market data and has deferred the conversation because fixing it is expensive — and when she leaves, the exit interview will say something true and substantively incomplete.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-28",
    slug: "built-to-fail",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Built to Fail",
    teaser: "You took the job because it looked like the right next step. Six months in, you understand exactly why the last person left. The scope was never realistic — and the organization keeps restaffing the role rather than redesigning it, because restaffing feels like progress and redesigning feels like admitting a mistake.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-29",
    slug: "the-paper-tiger",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Paper Tiger",
    teaser: "Everyone already knows this person shouldn't still be on the team. The conversations have happened more than once — in one-on-ones, in hallway asides, in performance reviews that somehow, every cycle, come out fine. The personnel file describes one employee. The conversations describe a completely different one.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-30",
    slug: "the-unsolved-problem",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Unsolved Problem",
    teaser: "There was a complaint, a while back. It went through the right process — investigated, addressed, formally closed. The behavior that caused it didn't move on at all. What got resolved was the paperwork. The condition underneath it was never what anyone addressed.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-31",
    slug: "the-tolerated-violation",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Tolerated Violation",
    teaser: "There's a practice that people know is wrong. Not unclear or debatable — known, ubiquitous. It continues because the person at the center of it is protected or privileged, and because somewhere along the way it was calculated that the risk of letting it continue was smaller than the discomfort of confronting it.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-32",
    slug: "the-unreported-hazard",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Unreported Hazard",
    teaser: "There's a safety concern in this organization right now — physical, psychological, operational. People know about it. It hasn't been formally reported. The silence is a separate finding from the hazard itself, and it's the one that will produce the next hazard nobody reports either.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-33",
    slug: "the-unlocked-door",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Unlocked Door",
    teaser: "A known vulnerability exists in this organization. Not hidden, not undiscovered — known, named, and sitting there unaddressed. Not because nobody's seen it. Because the mechanism for closing it has never been used.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-34",
    slug: "dueling-narratives",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Dueling Narratives",
    teaser: "Two different accounts of what happened are circulating in this organization right now, and both have real authority behind them. The organization isn't operating from one shared understanding of a significant event. It's operating from two, simultaneously — and everyone navigating it has to decide privately which reality they're acting on.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-35",
    slug: "narrative-lock",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Narrative Lock",
    teaser: "This organization has an official account of itself, and it defends that account against evidence. People who contradict the official narrative, even with solid information, don't get heard. They get handled — because the people holding the narrative have more power than the people who can see it's wrong.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-36",
    slug: "the-wrong-reward",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Wrong Reward",
    teaser: "The behaviors that get rewarded here and the behaviors leadership says it values are not the same list. Nobody needed to be told the real criteria. People ran the experiment themselves, watched which behaviors moved careers, and the organization is getting exactly the behavior it's paying for.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-37",
    slug: "groundhog-day",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Groundhog Day",
    teaser: "This problem has been solved before. There was a task force, an initiative, a few months of real visible energy — and then, without any single dramatic reversal, everything drifted back to almost exactly where it started. The initiatives aren't failing. They're succeeding at the wrong target.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-38",
    slug: "the-founders-grip",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Founder's Grip",
    teaser: "Nothing moves without one person's approval, and everyone else has learned to plan around it. The people who couldn't live with the wait already left.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-39",
    slug: "invisible-influence-architecture",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Invisible Influence Architecture",
    teaser: "The org chart says who has authority. It doesn't say who actually decides anything — and by now you've stopped checking it.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-40",
    slug: "the-fracture",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Fracture",
    teaser: "Two leaders at the top are in open conflict, and everyone below has already picked a side. The work that needs both of them is exactly the work that isn't happening.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-41",
    slug: "hr-capture",
    contentType: "methodology",
    voice: "from_the_author",
    title: "HR Capture",
    teaser: "HR reports to the person it's supposed to watch. If you have a concern about them, you already know not to bring it there.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-42",
    slug: "transition-paralysis",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Transition Paralysis",
    teaser: "A leadership change is underway and the whole organization has quietly stalled around it, one reasonable deferral at a time.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-43",
    slug: "the-exposed",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Exposed",
    teaser: "There is no functioning HR here. There are employees, obligations, and risk — and nobody whose job it is to manage any of it.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-44",
    slug: "the-uninitiated",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Uninitiated",
    teaser: "Something consequential is coming and this organization has never done it before. Capable and underprepared aren't the same thing.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-45",
    slug: "paper-shield",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Paper Shield",
    teaser: "The policies are current, the training is documented, the forms are signed. None of it describes what actually happens here.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-46",
    slug: "the-pay-fog",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Pay Fog",
    teaser: "The numbers don't make sense and nobody can explain why. Pay transparency is about to make that a much harder question to dodge.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-47",
    slug: "the-arbitrary-standard",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Arbitrary Standard",
    teaser: "The rules don't apply the same way to everyone, and people have decoded exactly who they bend for.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-48",
    slug: "the-unexamined-algorithm",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Unexamined Algorithm",
    teaser: "A tool is making real employment decisions here. Nobody has checked what it's actually optimizing for.",
    citationIds: ["HC-NYCLL144-2023", "HC-MOBLEY-2024"],
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-49",
    slug: "the-second-close",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Second Close",
    teaser: "The deal closed months ago. The organization didn't. Two companies are still running under one name.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-50",
    slug: "invisible-burnout",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Invisible Burnout",
    teaser: "You're hitting every number. The exhaustion isn't in any metric the organization is tracking.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-51",
    slug: "the-culture-that-wasnt",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Culture That Wasn't",
    teaser: "The all-hands still describes who this company used to be. Everyone who's been here long enough knows the gap.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-52",
    slug: "the-inside-track",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Inside Track",
    teaser: "Certain people move faster here than their output explains. What they have is proximity, not performance.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "FTA-53",
    slug: "the-diversity-ceiling",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Diversity Ceiling",
    teaser: "Representation looks strong at entry level and collapses above a line everyone below it can already see.",
    author: "Principal Resolution",
    status: "published",
  },
  {
    id: "LIB-052",
    slug: "what-not-to-document",
    contentType: "memo",
    voice: "standard",
    title: "What NOT to Document",
    teaser: "Most organizations document defensively and starve the documentation that actually protects people — the performance conversation, the commitment, the disagreement. The paper that creates real risk isn't the paper you're missing. It's the paper you didn't need.",
    relatedSlug: "paper-shield",
    citationIds: ["HC-SIXTH-BABB-2019", "HC-THIRD-TICE-2001", "HC-SCOTUS-MURRAYUBS-2024"],
    author: "Principal Resolution",
    status: "published",
    contentPillar: "Pattern Named",
  },
];
