export type BookContentType = "memo" | "methodology" | "case_pattern";
export type BookVoice = "standard" | "from_the_author";

export interface BookPiece {
  id: string;
  slug: string;
  contentType: BookContentType;
  voice: BookVoice;
  title: string;
  teaser: string;
  signatureId?: string;
  citationIds?: string[];
  relatedSlug?: string;
  author: "Principal Resolution";
  status: "draft" | "published" | "parked";
}

export const bookManifest: BookPiece[] = [
  {
    id: "LIB-020",
    slug: "candor-as-an-organizational-variable",
    contentType: "methodology",
    voice: "standard",
    title: "Candor as an Organizational Variable: What It Is, How It Degrades, and What the Instrument Reads",
    teaser: "Candor is not a personality trait or a cultural value statement. It is a measurable organizational condition with known degradation patterns and known consequences for diagnostic accuracy.",
    citationIds: ["HC-007", "HC-110"],
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-021",
    slug: "symptoms-states-and-why-the-distinction-matters",
    contentType: "methodology",
    voice: "standard",
    title: "Symptoms, States, and Why the Distinction Matters for Practice",
    teaser: "Organizations present with symptoms. The instrument diagnoses states. Understanding why those are different things — and why treating one without identifying the other produces recurrence — is foundational to how Principal Resolution works.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-025",
    slug: "when-the-data-points-at-the-person-who-hired-you",
    contentType: "methodology",
    voice: "standard",
    title: "When the Data Points at the Person Who Hired You",
    teaser: "The diagnostic implicates leadership. The person who hired you is sitting across from you. What happens in the next twenty-four hours will define the engagement more than anything that came before it.",
    citationIds: ["HC-068", "HC-070"],
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-026",
    slug: "the-problem-they-brought-you-is-not-always-the-problem",
    contentType: "methodology",
    voice: "standard",
    title: "The Problem They Brought You Is Not Always the Problem",
    teaser: "Clients arrive with a theory. The diagnostic arrives with a finding. Understanding why those two things diverge — and how to navigate the gap without losing the client — is one of the hardest skills in the work.",
    citationIds: ["HC-071"],
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-027",
    slug: "how-to-tell-if-the-organization-will-actually-change",
    contentType: "methodology",
    voice: "standard",
    title: "How to Tell If the Organization Will Actually Change",
    teaser: "Every organization that hires a practitioner believes it is ready to change. Learning to distinguish genuine readiness from its performance — before the engagement is half over — is one of the most valuable skills in the work.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-028",
    slug: "what-their-resistance-is-actually-telling-you",
    contentType: "methodology",
    voice: "standard",
    title: "What Their Resistance Is Actually Telling You",
    teaser: "Resistance is not the end of an engagement's productive life. It is often the beginning of it. What the organization is pushing back against tells you more about where the work needs to go than anything it has said directly.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-030",
    slug: "earned-effectiveness-conversation-framework",
    contentType: "methodology",
    voice: "standard",
    title: "The Earned Effectiveness Conversation Framework: Sequence, Accuracy, and What the Practice Debrief Reads",
    teaser: "Effectiveness in a hard conversation is never assumed and never forced — it is earned through a disciplined sequence. This piece explains the framework and what the four practice debrief dimensions are actually measuring.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-034",
    slug: "earned-effectiveness",
    contentType: "methodology",
    voice: "standard",
    title: "Earned Effectiveness",
    teaser: "Most practitioners know how to be direct. Fewer know how to be direct in a way that produces change rather than defense. The gap between those two outcomes is not a matter of courage or clarity — it is a matter of sequence.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-17",
    slug: "anchor",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Anchor",
    teaser: "The Anchor is the rarest finding in the diagnostic system — not because healthy organizations are rare, but because they don't usually go looking. What you built is real, it's valuable, and it's more fragile than it looks.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-014",
    slug: "anchor-problem",
    contentType: "memo",
    voice: "standard",
    title: "The Anchor Problem",
    teaser: "Anchor is the state that names what happens when a role, a person, or a structure that once worked has not been updated to match what the organization has become. The drag compounds quietly — and adaptation is not resolution.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-013",
    slug: "exit-calculation",
    contentType: "memo",
    voice: "standard",
    title: "The Exit Calculation",
    teaser: "The people who left were not wrong. They were just the first to finish the math. The ones still here are running the same calculation — and they are watching to see what you do next.",
    relatedSlug: "exit-pattern",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-015",
    slug: "feedback-nobody-wants-to-say",
    contentType: "memo",
    voice: "standard",
    title: "The Thing About Feedback Nobody Wants to Say",
    teaser: "The corporate feedback apparatus has become extraordinarily sophisticated at creating the appearance of feedback without producing the substance of it. The problem is not the tools — we confused delivery infrastructure with candor.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-016",
    slug: "psychological-safety-walked-into-a-meeting",
    contentType: "memo",
    voice: "standard",
    title: "Psychological Safety Walked Into a Meeting",
    teaser: "This is not an argument against psychological safety. It is an argument against what most organizations have done with a genuinely useful idea — deploy it in exactly the environments where it cannot survive.",
    citationIds: ["HC-068"],
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-017",
    slug: "hr-is-the-table",
    contentType: "memo",
    voice: "standard",
    title: "HR Is the Table",
    teaser: "The 'seat at the table' argument was always asking for the wrong thing. HR is not seeking entry into a room where decisions are being made. HR is the architecture that makes the room possible.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-035",
    slug: "organizational-assessment",
    contentType: "memo",
    voice: "standard",
    title: "Organizational Assessment",
    teaser: "An organizational assessment sends someone in with no position in the organization, no relationships to protect, and no stake in what the findings turn out to be. What it produces is a diagnosis — not a set of recommendations designed to be palatable.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-036",
    slug: "organizational-assessment-methodology",
    contentType: "methodology",
    voice: "standard",
    title: "Organizational Assessment: Methodology",
    teaser: "Most consulting engagements begin with a hypothesis — and the investigation confirms it. Three principles that correct for this: look without an agenda, report what you actually found, and deliver something specific enough to act on.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-037",
    slug: "organizational-assessment-sop",
    contentType: "methodology",
    voice: "standard",
    title: "Organizational Assessment: Engagement SOP",
    teaser: "The full engagement sequence for an organizational assessment — five phases, none compressible — with guidance for the circumstances where something in the engagement doesn't fit the expected pattern.",
    author: "Principal Resolution",
    status: "parked",
  },
  {
    id: "FTA-03",
    slug: "succession-planning",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Succession Planning",
    teaser: "The difference between a succession plan and a succession wish — and what organizational continuity actually requires you to be able to answer.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-06",
    slug: "business-case",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Business Case",
    teaser: "Business cases aren't predictions. They're arguments optimized for approval — and the system that rewards the confident version over the accurate one keeps producing the same outcomes.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-10",
    slug: "accountability",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Accountability",
    teaser: "Accountability doesn't collapse all at once. It erodes through exceptions — each one defensible in isolation, accumulating into a permission structure that everyone can see and no one has addressed.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-11",
    slug: "matrix-organization",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Matrix Organization",
    teaser: "The matrix doesn't eliminate reporting conflict. It relocates it downward — to the person with the least power to resolve it — and calls that structure.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-12",
    slug: "toxic-culture",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Toxic Culture",
    teaser: "Toxic cultures don't announce themselves. They teach you the rules the old-fashioned way — by making examples — and become stable long before anyone decides to address them.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-01",
    slug: "the-untouchable",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Untouchable",
    teaser: "You know exactly who it is. You've done the math on what it's costing. Leadership has done the math too — and decided the answer is to keep waiting. That calculation is almost always wrong.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-02",
    slug: "leadership-deafness",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Leadership Deafness",
    teaser: "The leader who talks about transparency and shuts down the moment someone tests it. The feedback that stopped reaching them years ago. The gap between who they think they are and what the room experiences.",
    citationIds: ["HC-103"],
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-04",
    slug: "no-margin-for-error",
    contentType: "methodology",
    voice: "from_the_author",
    title: "No Margin for Error",
    teaser: "You already know it's bad. The buffer is gone. The people who could help you fix this are the ones who have already left. The window is real — and it is not going to stay open while you think about it.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-05",
    slug: "exit-pattern",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Identity Erosion",
    teaser: "Another one just put in notice. The exit interviews say 'opportunity.' The real story is what they tell their friends six months later, once they have nothing to lose. You are not losing people randomly. You are losing people in a pattern.",
    relatedSlug: "exit-calculation",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-07",
    slug: "the-basement-standard",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Basement Standard",
    teaser: "Everyone knows. Nobody says anything. The organization decided, without ever really deciding, that avoiding conflict is more important than solving problems. The cost is invisible until it isn't.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-08",
    slug: "silosolation",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Silosolation",
    teaser: "The organization has fractured into self-contained units that have learned to function without each other. Each team is doing fine on their own. The whole is producing less than the sum of its parts — and the gap between the two is where your best people are slowly burning out.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-09",
    slug: "the-broken-compass",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Broken Compass",
    teaser: "The offsite was great. Everyone left feeling aligned. That was three months ago. Since then, the same agreed strategy has been interpreted six different ways — and nobody has acknowledged the contradiction because acknowledging it would require having the conversation that nobody wants to have.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-13",
    slug: "decision-paralysis",
    contentType: "methodology",
    voice: "from_the_author",
    title: "Decision Paralysis",
    teaser: "The meeting moves. The agenda advances. Everyone nods. You walk out and realize nothing was actually decided. Again. This is not professionalism — it is the language of thoughtfulness deployed in the service of permanent deferral.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-14",
    slug: "the-undefined-role",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Undefined Role",
    teaser: "The org chart you drew at twenty people does not work at eighty. The roles blurred in motion, the workarounds became the system, and the people who absorbed the gap are now the first ones running the math on how much longer they can sustain it.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-15",
    slug: "the-policy-lag",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Policy Lag",
    teaser: "You are not failing because you are bad at your job. You are failing because you are running today's operations on infrastructure built for a different organization. The process was good once. That organization no longer exists.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "FTA-16",
    slug: "the-lost-map",
    contentType: "methodology",
    voice: "from_the_author",
    title: "The Lost Map",
    teaser: "You are not sure what is wrong. You are sure something is. The signals are present but have not formed a pattern yet. That ambiguity is frustrating — and it is also the most valuable moment to be paying attention.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-018",
    slug: "everyone-is-defensive-and-no-one-knows-why",
    contentType: "memo",
    voice: "standard",
    title: "Everyone Is Defensive and No One Knows Why",
    teaser: "You have started preparing for conversations that should take five minutes. Feedback stopped being a tool and became a risk — not because anyone decided that, but through small, accumulated signals that added up to something legible: raising difficult things here costs more than staying quiet.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-019",
    slug: "the-room-that-never-pushes-back",
    contentType: "memo",
    voice: "standard",
    title: "The Room That Never Pushes Back",
    teaser: "Your meetings go smoothly. Proposals land well. Nobody raises objections you haven't already thought of. A room that never pushes back is not a room full of people who agree with you — it is a room full of people who have decided that disagreeing with you costs more than it returns.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-022",
    slug: "what-the-organization-decided-he-was-worth",
    contentType: "case_pattern",
    voice: "standard",
    title: "What the Organization Decided He Was Worth",
    teaser: "A director. A CEO friendship. An HR function without standing. Two women who followed the process exactly as designed — and found out what the process was built to protect. The complaint worked. That was the problem.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-023",
    slug: "the-first-one-out-the-door",
    contentType: "case_pattern",
    voice: "standard",
    title: "The First One Out the Door",
    teaser: "She had been there six years. When she resigned, the executive director said it was a loss but that he understood. What he did not do — what nobody did — was ask her what she had been watching for the last eighteen months.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-024",
    slug: "why-your-team-stopped-disagreeing-with-you",
    contentType: "memo",
    voice: "standard",
    title: "Why Your Team Stopped Disagreeing with You",
    teaser: "You put a real question to your senior team — one where you genuinely expected the table to split — and instead you got unanimous agreement. You are left wondering whether you just got consensus or whether you got a performance of it. Those are not the same thing.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-029",
    slug: "the-resignation-that-ended-a-department",
    contentType: "case_pattern",
    voice: "standard",
    title: "The Resignation That Ended a Department",
    teaser: "She had been there eleven years — long enough to become the person who keeps an organization functioning in ways nobody thought to measure. The restructuring disrupted something invisible. She raised it in March. She resigned in April. What the transition checklist could not capture left with her.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-031",
    slug: "what-ready-didnt-include",
    contentType: "case_pattern",
    voice: "standard",
    title: "What Ready Didn't Include",
    teaser: "She was not excluded. She was simply not included at the moment when inclusion would have changed something. That distinction matters — because the first version of the problem is about intent, and the second is about structure. Intent is easy to defend. Structure is what actually determines what information reaches a decision.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-032",
    slug: "one-exception-at-a-time",
    contentType: "case_pattern",
    voice: "standard",
    title: "One Exception at a Time",
    teaser: "The strategy was real. The exceptions were reasonable. By the fourth exception, no one was calling them exceptions anymore. Drift is not a single decision — it is the product of many reasonable decisions that no one ever accounted for together.",
    author: "Principal Resolution",
    status: "draft",
  },
  {
    id: "LIB-033",
    slug: "built-for-comfort",
    contentType: "case_pattern",
    voice: "standard",
    title: "Built for Comfort",
    teaser: "He had not been wrong often. Over thirty years, that accumulated into something that looked like wisdom and functioned like a wall. He did not construct the architecture deliberately. He maintained it passively, one comfortable hire at a time.",
    author: "Principal Resolution",
    status: "draft",
  },
];
