"""Ranker test 02: coarse-level test under R0, to the definitions frozen in prompts/ranker-test-02-preregistration.md
(commit 229198f). Every figure is generated here from the saved run files or live calls into the production engine.

M1 dimension hit: R0 rank-1 state's primary dimension equals the target's.
M2 family hit: R0 rank-1 state's resolution family (split on " + ") shares a component with the target's.
M3 dimension top-3 hit: any of the R0 top 3 shares the target's primary dimension.
Data: the 13 Ranker Test 01 paths (reusing tools/ranker_test_01.py's loader and R0 replay) and the 175 calibration profiles.

Usage:
  python tools/ranker_test_02.py                       # print the RESULTS section
  python tools/ranker_test_02.py --append --dry-run    # check append-only
  python tools/ranker_test_02.py --append --write      # append to prompts/ranker-test-02-preregistration.md
"""
import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import tools.ranker_test_01 as rt1  # noqa: E402
import tools.calibration_runner as cr  # noqa: E402
from engine.accumulation import IntakeData, AccumulationEngine  # noqa: E402
from engine.data.questions import QUESTION_LIBRARY  # noqa: E402
from engine.data.salience import SALIENCE_PROFILES  # noqa: E402
from engine.data.states import STATE_PROFILES  # noqa: E402

PREREG = ROOT / "prompts" / "ranker-test-02-preregistration.md"
dim = lambda s: STATE_PROFILES[s].primary_dimension
fam = lambda s: set(STATE_PROFILES[s].resolution_family.split(" + "))
DIM_SHARE = {d: sum(1 for s in STATE_PROFILES if dim(s) == d) / len(STATE_PROFILES) for d in {dim(s) for s in STATE_PROFILES}}
yn = lambda b: "Y" if b else "N"


def measures(ids_in_order, target):
    top = ids_in_order[0]
    return {"lead": top, "m1": dim(top) == dim(target), "m2": bool(fam(top) & fam(target)),
            "m3": any(dim(s) == dim(target) for s in ids_in_order[:3]), "top3": ids_in_order[:3]}


def build():
    L = []
    w = L.append
    paths = rt1.load_paths()
    rows13, excl = [], []
    for p in paths:
        s0, order0 = rt1.r0_scores(p["intake"], p["answers"])
        o = rt1.ordered(s0)
        live = p["live"]
        ok = [s for s, _ in o[: len(live)]] == [x["state_id"] for x in live] and max(abs(v - x["score"]) for (_, v), x in zip(o, live)) < 5e-7
        if not ok:
            excl.append(p["id"])
            continue
        m = measures([s for s, _ in o], p["target"])
        m.update({"id": p["id"], "target": p["target"], "rank": [s for s, _ in o].index(p["target"]) + 1})
        rows13.append(m)
    w("")
    w("## RESULTS")
    w("")
    w("Produced by `tools/ranker_test_02.py` (committed with this section) to the definitions frozen at `229198f`. The text above this section is unchanged. Every figure is generated by the script. The 13 paths reuse the Ranker Test 01 loader and R0 replay (`tools/ranker_test_01.py`). The 175 profiles are replayed exactly as `tools.calibration_runner._run_profile_core` answers and accumulates them.")
    w("")
    w(f"Replay validity on the 13 paths: valid {len(rows13)} of {len(paths)}. Exclusions: {', '.join(excl) or 'none'}.")
    w("")
    w("### The 13 paths")
    w("")
    w("| Path | Target | Target dimension | Target families | Target rank | R0 rank-1 state | Rank-1 dimension | Rank-1 families | M1 | M2 | Top-3 dimensions | M3 |")
    w("|---|---|---|---|---:|---|---|---|:-:|:-:|---|:-:|")
    for m in rows13:
        w(f"| {m['id']} | {m['target']} | {dim(m['target'])} | {STATE_PROFILES[m['target']].resolution_family} | {m['rank']} | {m['lead']} | {dim(m['lead'])} | {STATE_PROFILES[m['lead']].resolution_family} | {yn(m['m1'])} | {yn(m['m2'])} | {', '.join(dim(s) for s in m['top3'])} | {yn(m['m3'])} |")
    n = len(rows13)
    M1 = sum(m["m1"] for m in rows13)
    M2 = sum(m["m2"] for m in rows13)
    M3 = sum(m["m3"] for m in rows13)
    chance1 = sum(DIM_SHARE[dim(m["target"])] for m in rows13)
    w("")
    w(f"Totals over {n} valid paths: M1 **{M1}**, M2 **{M2}**, M3 **{M3}**. Chance baseline for M1 (expected hits if rank 1 were a uniform draw over the 58 states, from the target dimensions' state shares): {chance1:.2f} of {n}.")
    w("")
    # 175
    profiles = list(cr.ALL_PROFILES)
    rows175 = []
    for tc in profiles:
        eng = AccumulationEngine(IntakeData(**tc.intake))
        for a in (tc.answers or cr.generate_answers(tc)):
            q = QUESTION_LIBRARY[a.question_id]
            for oid in a.selected_option_ids:
                eng.apply_answer(next(o for o in q.answer_options if o.option_id == oid), a.question_id)
        ids = [r.state_id for r in eng.rank(SALIENCE_PROFILES)]
        m = measures(ids, tc.target_state)
        m.update({"pt": tc.profile_type, "target": tc.target_state, "id": tc.test_id, "rank": ids.index(tc.target_state) + 1})
        rows175.append(m)
    w("### The 175 calibration profiles")
    w("")
    w("| Profile type | n | M1 | M2 | M3 | Target is rank 1 |")
    w("|---|---:|---:|---:|---:|---:|")
    for pt in cr.PROFILE_TYPES:
        rs = [r for r in rows175 if r["pt"] == pt]
        if rs:
            w(f"| {pt} | {len(rs)} | {sum(r['m1'] for r in rs)} | {sum(r['m2'] for r in rs)} | {sum(r['m3'] for r in rs)} | {sum(r['rank'] == 1 for r in rs)} |")
    N = len(rows175)
    A1, A2, A3 = (sum(r[k] for r in rows175) for k in ("m1", "m2", "m3"))
    w(f"| **all** | {N} | **{A1}** | **{A2}** | **{A3}** | {sum(r['rank'] == 1 for r in rows175)} |")
    chance175 = sum(DIM_SHARE[dim(r["target"])] for r in rows175)
    w("")
    w(f"Chance baseline for M1 over the 175 profiles: {chance175:.1f} of {N}.")
    w("")
    w("Rank-1 dimension against target dimension, all 175 profiles (rows target, columns rank-1 state):")
    w("")
    dims = sorted(DIM_SHARE)
    mat = defaultdict(Counter)
    for r in rows175:
        mat[dim(r["target"])][dim(r["lead"])] += 1
    w("| Target \\ Rank-1 | " + " | ".join(dims) + " |")
    w("|---|" + "---:|" * len(dims))
    for d in dims:
        w(f"| {d} | " + " | ".join(str(mat[d][e]) for e in dims) + " |")
    w("")
    leads = Counter(r["lead"] for r in rows175)
    w("Most frequent R0 rank-1 states across the 175 profiles: " + ", ".join(f"{s} ({dim(s)}) {c}" for s, c in leads.most_common(8)) + ".")
    w("")
    w("### Hypotheses, scored per the frozen arithmetic")
    w("")
    c1 = 5 <= M1 <= 8
    w(f"- **C1** (M1 on the 13 paths is 5 to 8, not 10 or more): **{'HOLDS' if c1 else 'FAILS'}**. M1 = {M1} of {n}." + ("" if c1 or M1 != 9 else " (9 is outside both the range and the 10-or-more exclusion.)"))
    w(f"- **C2** (M2 on the 13 paths is 7 or more): **{'HOLDS' if M2 >= 7 else 'FAILS'}**. M2 = {M2} of {n}.")
    w(f"- **C3** (M1 on the 175 profiles is 140 or more): **{'HOLDS' if A1 >= 140 else 'FAILS'}**. M1 = {A1} of {N}.")
    w(f"- M3 (no hypothesis): {M3} of {n} on the paths, {A3} of {N} on the profiles.")
    w("")
    return "\n".join(L)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--append", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    section = build()
    if not a.append:
        sys.stdout.reconfigure(encoding="utf-8")
        print(section)
        sys.exit(0)
    raw = PREREG.read_bytes()
    crlf = b"\r\n" in raw
    old = raw.decode("utf-8")
    base = old.rstrip("\r\n")
    assert "\n## RESULTS" not in base, "RESULTS section already present"
    new_text = base.replace("\r\n", "\n") + "\n" + section
    new = new_text.replace("\n", "\r\n") if crlf else new_text
    assert new.startswith(base), "existing text must be unchanged"
    print(f"append-only ok: {len(old)} -> {len(new)} chars, newline {'CRLF' if crlf else 'LF'}")
    if a.write:
        PREREG.write_bytes(new.encode("utf-8"))
        print("WROTE")
    else:
        print("DRY RUN")
